name: flutter_extras
description: Collection of common extensions and helper objects
version: 0.0.8+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.1 <3.0.0" #Dart SDK 8-Jun-2021
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.1

dev_dependencies:
  test: ^1.17.5

flutter:
  uses-material-design: true
