name: flutter_extras
description: Collection of common extensions and helper objects
version: 0.3.0+1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.3 <3.0.0" #Dart SDK 7-Oct-2021
  flutter: ">=2.5.2"

dependencies:
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  auto_size_text: ^3.0.0-nullsafety.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_platform_widgets: ^1.9.5
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  uuid: ^3.0.5

dev_dependencies:
  test: ^1.18.2

flutter:
  uses-material-design: true
