name: flutter_extras
description: Collection of common extensions and helper objects
version: 0.1.3+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  auto_size_text: ^3.0.0-nullsafety.0
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.1
  flutter_platform_widgets: ^1.9.5
  uuid: ^3.0.4

dev_dependencies:
  test: ^1.17.9

flutter:
  uses-material-design: true
