name: date_time_intervals
description: Template for Flutter Package project.
version: 0.1.0
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.1 <3.0.0" #Dart SDK 1-JUN-2021
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
