name: time_toggle_buttons
description: Creates a row of toggle buttons to select year, month, day, hour, minute, second
version: 0.0.4+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.3.0

dev_dependencies:
  test: ^1.17.9

flutter:
  uses-material-design: true
