name: persisted_cache
description: Class to handle persisted cache values, and widget to use cached values in TextField
version: 0.2.0+2
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.4 <3.0.0" #Dart SDK 2021-10-15
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  xfer:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: xfer
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.0
  flutter_bloc: ^8.0.0
  flutter_modular: ^4.2.0
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  popover: ^0.2.6+3

dev_dependencies:
  test: ^1.19.5

flutter:
  uses-material-design: true
