// Copyright 2021 LTMM, LLC. All rights reserved.
import 'package:enum_to_string/enum_to_string.dart';

enum CalendarDirection { between, sinceEnd, untilEnd }

enum CalendarItem {
  years,
  months,
  days,
  hours,
  minutes,
  seconds,
}

const Set<CalendarItem> AllCalendarItems = {
  CalendarItem.years,
  CalendarItem.months,
  CalendarItem.days,
  CalendarItem.hours,
  CalendarItem.minutes,
  CalendarItem.seconds,
};

/// Helper function that turns a set of CalendarItem into a string for use as SQL data as a comma seperated string
String calendarItemsAsString(Set<CalendarItem> items) {
  String result = '';
  for (CalendarItem item in items) {
    if (result.length > 0) result += ',';
    result += EnumToString.convertToString(item);
  }
  return result;
}

/// Takes the string generated by [calendarItemsAsString] and creates a [Set<CalendarItem>], the use being
/// the [CalendarItem] can be saved then read from SQL database
Set<CalendarItem> calendarItemsFrom({required String string}) {
  Set<CalendarItem> result = Set();
  CalendarItem.values.forEach((element) {
    final key = EnumToString.convertToString(element).toLowerCase();
    if (string.toLowerCase().contains(key)) result.add(element);
  });
  return result;
}
