name: aguments
description: Add features to BuildContext
version: 0.0.3+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.3 <3.0.0" #Dart SDK 7-MAY-2021
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.0

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
