name: maps_launcher
description: Simple Flutter plugin to open the maps application (or browser) on all platforms.
version: 1.3.0+0
homepage: https://github.com/pikaju/flutter-maps-launcher
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.icodeforyou.maps_launcher
        pluginClass: MapsLauncherPlugin
      ios:
        pluginClass: MapsLauncherPlugin
      linux:
        pluginClass: MapsLauncherPlugin
      web:
        pluginClass: MapsLauncherWeb
        fileName: maps_launcher_web.dart
