name: widget_size
description: Template for Flutter Package project.
version: 0.0.1+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.3 <3.0.0" #Dart SDK 7-MAY-2021
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
