name: scrolling_datetime_picker
description: Template for Flutter Package project.
version: 0.1.1+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.3 <3.0.0"  #Dart SDK 7-MAY-2021
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: theme_manager
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  popover: ^0.2.6+1
  intl: ^0.17.0


dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
