name: popover_datetime_picker
description: Template for Flutter Package project.
version: 0.3.0
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.3 <3.0.0" #Dart SDK 18-JUN-2021
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: theme_manager
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_bloc: ^7.0.1
  intl: ^0.17.0
  popover: ^0.2.6+2

dev_dependencies:
  test: ^1.17.8

flutter:
  uses-material-design: true
