name: tracers_app
description: Runs demo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0+1

environment:
  sdk: ">=2.14.3 <3.0.0" #Dart SDK 7-Oct-2021
  flutter: ">=2.5.2"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tracers_package:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
