name: theme_management_package
description: Manages themes
version: 0.0.1+6
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  observing_stateful_widget:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: observing_stateful_widget
  xfer:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: xfer
  dartz: ^0.10.0-nullsafety.1
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0

dev_dependencies:
  test: ^1.16.8

flutter:
  uses-material-design: true
