name: animation_checkmark
description: Animates a checkmark
version: 0.0.5+3
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.17.9

flutter:
  uses-material-design: true
