name: theme_manager
description: Manages light and dark themes
version: 0.1.4+2
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  dartz: ^0.10.0-nullsafety.2
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
