name: date_time_picker_widget_package
description: Template for Flutter Package project.
version: 0.0.1+99
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  date_time_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: date_time_package
  observing_stateful_widget:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: observing_stateful_widget
  theme_management_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: theme_management_package
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  popover: ^0.2.1
  flutter_modular: ^3.0.2+1
  intl: ^0.17.0

dev_dependencies:
  coverage: ^1.0.1
  mocktail: ^0.1.0
  pedantic: ^1.10.0
  rxdart: ^0.26.0
  test: ^1.16.8

flutter:
  uses-material-design: true
