name: date_time_picker_widget_package
description: Template for Flutter Package project.
version: 0.0.1+99
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: theme_manager
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_bloc: ^7.0.0
  popover: ^0.2.6+1
  flutter_modular: ^3.2.2+1
  intl: ^0.17.0

dev_dependencies:
  coverage: ^1.0.3
  mocktail: ^0.1.4
  pedantic: ^1.11.0
  rxdart: ^0.26.0
  test: ^1.17.5

flutter:
  uses-material-design: true
