name: confirmation_popover
description: Displays two {or three} -button popover to confirm an action of widget.
version: 0.3.0+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.1 <3.0.0" #Dart SDK 1-JUN-2021
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  popover: ^0.2.6+1

dev_dependencies:
  test: ^1.17.5

flutter:
  uses-material-design: true
