name: observing_stateful_widget
description: Extend StatefulWidget callback afterFirstLayout, and notifiers for text scale change, platform brightness, lifecycle
version: 0.0.1+4
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8

flutter:
  uses-material-design: true
