name: network_connection_package
description: Tracks changes in network connectivity
version: 1.1.0
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
  test: ^1.16.5

flutter: null
