name: xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.12.4 <3.0.0" #Dart SDK 1-JUL-2021
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  date_time_intervals:
    path: ../
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  theme_manager:
    git:
      url: https://github.com/GitHubStuff/theme_manager.git
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.1
  flutter_modular: ^3.3.0

dev_dependencies:
  test: ^1.17.9

flutter:
  uses-material-design: true
