name: modular_transitions
description: Template for Flutter Package project.
version: 0.0.1+2
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.3 <3.0.0" #Dart SDK 7-MAY-2021
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_extras:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: flutter_extras
  flutter_modular: ^3.2.2+1

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
