name: theme_package
description: A new Flutter Theme package.
version: 0.11.0+1
author: Steven Smith
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_modular: ^3.0.3
  intl: ^0.17.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  app_exception:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: app_exception
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package

dependency_overrides:
  # Contains the FontAwesome-Pro icons.
  font_awesome_flutter:
    git:
      url: https://github.com/GitHubStuff/font_awesome_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
