name: theme_package
description: A new Flutter Theme package.
version: 0.10.0+0
author: Steven Smith
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.0-nullsafety.1
  equatable: ^2.0.0
  flutter_bloc: ^6.1.1
  flutter_modular: ^2.0.1
  intl: ^0.17.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  sqflite: ^1.3.2+1

dependency_overrides:
  # Contains the FontAwesome-Pro icons.
  font_awesome_flutter:
    path: ../font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
