name: app_exception
description: Template for Flutter Package project.
version: 0.0.1
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
