name: app_exception
description: Extends Exception for an enhanced description of an error
version: 0.0.4+1
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.13.3 <3.0.0" #Dart SDK 18-JUN-2021
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3

dependency_overrides: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
