name: xample
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.12.3 <3.0.0" #Dart SDK 7-MAY-2021

dependencies:
  flutter:
    sdk: flutter
  widget_size:
    path: ../
  theme_management_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: theme_management_package
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_modular: 3.2.2+1

dev_dependencies:
  test: ^1.17.4

flutter:
  uses-material-design: true
