name: json_decoder
description: Json Decoder with 'Safe'-decoding and decoding time feature
version: 1.0.4+2
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.2
  enum_to_string: ^2.0.1

dev_dependencies:
  test: ^1.17.3

flutter:
  uses-material-design: true
