name: xfer
description: Does http calls, and call to asset, and local files with various protocols
version: 0.0.1+4
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.12.0 <3.0.0" #dart
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0-nullsafety.1
  enum_to_string: ^2.0.1
  equatable: ^2.0.0
  http: ^0.13.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - onboarding/
