name: xfer
description: Does http calls, and call to asset, and local files with various protocols
version: 0.4.1+3
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.13.3 <3.0.0" #Dart SDK 18-JUN-2021
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  tracers_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: tracers_package
  cached_network_image: ^3.1.0-alpha.1
  dartz: ^0.10.0-nullsafety.2
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - onboarding/
    - onboarding/bird.png
