name: tracers_package
description: Write messages to the console
version: 1.3.3+1
author: Steven Smith
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  date_time_package:
    git:
      url: https://github.com/GitHubStuff/flutter_packages.git
      path: date_time_package
  dartz: ^0.10.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
