name: tracers_package
description: Write messages to the console
version: 1.9.1+1
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.14.3 <3.0.0" #Dart SDK 7-Oct-2021
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
